variables:
    DOCKER_DRIVER: "overlay2"
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: "/certs"
    MYSQL_ROOT_PASSWORD: "root"
    MYSQL_USER: "app"
    MYSQL_PASSWORD: "app"
    MYSQL_DATABASE: "shopware"
    SW_HOST: "localhost"
    SW_BASE_PATH: ""
    WEB_DOCUMENT_ROOT: "$CI_PROJECT_DIR/"
    ARTIFACTS_ROOT: "$CI_PROJECT_DIR/artifacts"
    GIT_STRATEGY: "clone"
    CHECKOUT_SHOPWARE_BRANCH: "5.7"
    PLUGIN_NAME: "SwagPaymentPayPalUnified"
    DB_USER: "app"
    DB_PASSWORD: "app"
    DB_HOST: "mysql"
    DB_PORT: 3306
    DB_NAME: "shopware"

stages:
    - Code Analysis
    - PHPUnit
    - Shopware Versions
    - E2E

default:
    tags:
        - t3.medium
    image: gitlab.shopware.com:5005/shopware/5/product/image/continuous:7.4

.prepare_files_script: &prepare_files_script
    - composer install --no-dev
    - composer dump-autoload
    - zip -rq plugin.zip .
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/5/product/shopware.git shopware --depth=1 -b ${CHECKOUT_SHOPWARE_BRANCH}
    - unzip -q plugin.zip -d shopware/custom/plugins/${PLUGIN_NAME}
    - composer install -q -d shopware
    - cd shopware

.prepare_files_script_cookie_consent_manager: &prepare_files_script_cookie_consent_manager
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/5/product/swagcookieconsentmanager.git custom/plugins/SwagCookieConsentManager -b ${CHECKOUT_COOKIE_CONSENT_MANAGER_BRANCH}

.prepare_installation_script_install_shopware: &prepare_installation_script_install_shopware
    - sed -e "s/%db\.user%/${MYSQL_USER}/g" -e "s/%db\.password%/${MYSQL_PASSWORD}/g" -e "s/%db\.database%/${MYSQL_DATABASE}/g" -e "s/%db\.host%/mysql/g" -e "s/%db\.port%/3306/g" < config.php.dist > config.php
    - php bin/console sw:database:setup --steps=drop,create,import,importDemodata
    - php bin/console sw:cache:clear
    - php bin/console sw:database:setup --steps=setupShop --shop-url=http://${SW_HOST}${SW_BASE_PATH}
    - php bin/console sw:snippets:to:db --include-plugins
    - php bin/console sw:theme:initialize
    - php bin/console sw:firstrunwizard:disable
    - php bin/console sw:admin:create --name="Demo" --email="demo@demo.de" --username="demo" --password="demo" --locale=de_DE -n
    - touch recovery/install/data/install.lock

.prepare_installation_script_install_shopware_make: &prepare_installation_script_install_shopware_make
    - eval export DB_USER DB_PASSWORD DB_HOST DB_PORT DB_NAME SW_HOST SW_BASE_PATH
    - make init

.prepare_installation_script_install_plugin: &prepare_installation_script_install_plugin
    - php bin/console sw:plugin:refresh
    - php bin/console sw:plugin:install --activate ${PLUGIN_NAME}
    - php bin/console sw:cache:clear

.prepare_installation_script_install_cookie_consent_manager_plugin: &prepare_installation_script_install_cookie_consent_manager_plugin
    - php bin/console sw:plugin:refresh
    - php bin/console sw:plugin:install --activate SwagCookieConsentManager
    - php bin/console sw:cache:clear

.entrypoint_script: &entrypoint_script
    - /usr/bin/supervisord -c /etc/supervisord.conf &>/dev/null &

.phpunit_base:
    stage: PHPUnit
    services:
        - name: mysql:5.7
          alias: mysql
    before_script:
        - *prepare_files_script
        - *prepare_installation_script_install_shopware_make
        - *prepare_installation_script_install_plugin
        - *entrypoint_script
        - cd custom/plugins/${PLUGIN_NAME}
    script:
        - ../../../vendor/bin/phpunit -v --config="phpunit.xml.dist" --colors="never" --log-junit="${ARTIFACTS_ROOT}/test-log.junit.xml"
    artifacts:
        paths:
            - ${ARTIFACTS_ROOT}
        reports:
            junit: ${ARTIFACTS_ROOT}/*.junit.xml

.phpunit_base_pre_v57:
    extends: .phpunit_base
    before_script:
        - composer self-update --1
        - *prepare_files_script
        - *prepare_installation_script_install_shopware
        - *prepare_installation_script_install_plugin
        - cd custom/plugins/${PLUGIN_NAME}

.phpunit_base_pre_v56:
    extends: .phpunit_base
    image: gitlab.shopware.com:5005/shopware/5/product/image/continuous:7.2
    before_script:
        - composer self-update --1
        - *prepare_files_script
        - *prepare_files_script_cookie_consent_manager
        - *prepare_installation_script_install_shopware
        - *prepare_installation_script_install_plugin
        - *prepare_installation_script_install_cookie_consent_manager_plugin
        - cd custom/plugins/${PLUGIN_NAME}

.phpunit_base_pre_v53:
    extends: .phpunit_base_pre_v56
    image: gitlab.shopware.com:5005/shopware/5/product/image/continuous:5.6

JavaScript checks:
    tags:
        - t3.nano
    stage: Code Analysis
    image: node:alpine
    services: []
    before_script:
        - apk add --no-cache make bash zip unzip git
        - zip -rq plugin.zip .
        - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/5/product/shopware.git shopware --depth=1 -b ${CHECKOUT_SHOPWARE_BRANCH}
        - unzip -q plugin.zip -d shopware/custom/plugins/${PLUGIN_NAME}
    script:
        - cd shopware
        - make install-theme-depencencies
        - cd custom/plugins/${PLUGIN_NAME}
        - (cd Tests/E2E && npm install)
        - make check-js-code
        - make run-javascript-tests

PHP analyze:
    extends: .phpunit_base
    stage: Code Analysis
    script:
        - composer require --dev phpcompatibility/php-compatibility
        - ./vendor/bin/phpcs --config-set installed_paths vendor/phpcompatibility/php-compatibility
        - ./vendor/bin/phpcs -p --ignore="./vendor/" --standard="PHPCompatibility" --runtime-set testVersion 5.6 ./
        - make fix-cs-dry
        - php ../../../bin/console -e production -q # Initialise DIC (var/cache/production____REVISION____) for phpstan
        - >
            if [ $CI_PIPELINE_SOURCE == "schedule" ]; then
                sed -i "s|reportUnmatchedIgnoredErrors: true|reportUnmatchedIgnoredErrors: false|g" phpstan.neon
            fi
        - make phpstan
    artifacts:

Code Coverage:
    extends: .phpunit_base
    script:
        - php -d pcov.enabled="1" -d pcov.directory="${CI_PROJECT_DIR}" -d pcov.exclude='~(vendor|Tests)~'
            ../../../vendor/bin/phpunit
            --configuration="phpunit.xml.dist"
            --colors="never"
            --log-junit="${ARTIFACTS_ROOT}/phpunit.junit.xml"
            --coverage-cobertura=${ARTIFACTS_ROOT}/phpunit-coverage.cobertura.xml
            --coverage-text | sed -E -n '1,/^\s*Lines:\s*([0-9]+(\.[0-9]+)?)%/ p' # See: https://gitlab.shopware.com/shopware/6/product/platform/-/blob/trunk/.gitlab/stages/02-unit.yml#L92
        - sed -i 's/\/shopware\/custom\/plugins\/SwagPaymentPayPalUnified//' ${ARTIFACTS_ROOT}/phpunit-coverage.cobertura.xml # Remove the shopware installation part from the <sources> tag, so the coverage paths are relative to the original plugin root again, not the one inside custom/plugins.
    coverage: '/^\s*Lines:\s*(\d+(?:\.\d+)?%)/'
    artifacts:
        reports:
            junit: ${ARTIFACTS_ROOT}/*.junit.xml
            cobertura: ${ARTIFACTS_ROOT}/*.cobertura.xml
        expire_in: 1 week

SW 5.2:
    extends: .phpunit_base_pre_v53
    stage: Shopware Versions
    variables:
        CHECKOUT_SHOPWARE_BRANCH: "5.2"
        CHECKOUT_COOKIE_CONSENT_MANAGER_BRANCH: "5.2.11-5.2.27"

SW 5.3:
    extends: .phpunit_base_pre_v56
    stage: Shopware Versions
    variables:
        CHECKOUT_SHOPWARE_BRANCH: "5.3"
        CHECKOUT_COOKIE_CONSENT_MANAGER_BRANCH: "5.3.5-5.3.7"
    only:
        - master

SW 5.4:
    extends: .phpunit_base_pre_v56
    stage: Shopware Versions
    variables:
        CHECKOUT_SHOPWARE_BRANCH: "5.4"
        CHECKOUT_COOKIE_CONSENT_MANAGER_BRANCH: "5.4.6"
    only:
        - master

SW 5.5:
    extends: .phpunit_base_pre_v56
    stage: Shopware Versions
    variables:
        CHECKOUT_SHOPWARE_BRANCH: "5.5"
        CHECKOUT_COOKIE_CONSENT_MANAGER_BRANCH: "5.5.0-5.5.10"
    only:
        - master

SW 5.6:
    extends: .phpunit_base_pre_v57
    stage: Shopware Versions
    variables:
        CHECKOUT_SHOPWARE_BRANCH: "5.6"
    only:
        - master

SW 5.7 PHP 7.4:
    extends: .phpunit_base
    only:
        - master

SW 5.7 PHP 8.0:
    extends: .phpunit_base
    image: gitlab.shopware.com:5005/shopware/5/product/image/continuous:8.0

E2E:
    stage: E2E
    services:
        - name: mysql:5.7
          alias: mysql
    before_script:
        - sed -i -e "s;__ROOT__;$CI_PROJECT_DIR/shopware;g" /etc/nginx/sites-enabled/shopware.conf
        - /usr/bin/supervisord -c /etc/supervisord.conf &>/dev/null &
        - *prepare_files_script
        - *prepare_installation_script_install_shopware_make
        - *prepare_installation_script_install_plugin
        - mv config.php config-original.php
        - cp ./custom/plugins/${PLUGIN_NAME}/Tests/E2E/config.php config.php
        - chown -R www-data:www-data .
        - curl http://localhost/backend/ -v
    script:
        - apk add --no-cache make npm nodejs chromium chromium-chromedriver
        - cd custom/plugins/${PLUGIN_NAME}/Tests/E2E
        - npm install
        - >
         DEBUG=pw:browser* EXECUTION_PATH=/usr/bin/chromium-browser BASE_URL=http://${SW_HOST}
         PAYPAL_CUSTOMER_EMAIL=${PAYPAL_CUSTOMER_EMAIL} PAYPAL_CUSTOMER_PASSWORD=${PAYPAL_CUSTOMER_PASSWORD} PAYPAL_CREDIT_CARD=${PAYPAL_CREDIT_CARD}
         PAYPAL_SANDBOX_CLIENT_ID=${PAYPAL_SANDBOX_CLIENT_ID} PAYPAL_SANDBOX_CLIENT_SECRET=${PAYPAL_SANDBOX_CLIENT_SECRET} PAYPAL_SANDBOX_MERCHANT_ID=${PAYPAL_SANDBOX_MERCHANT_ID}
         MYSQL_HOST=mysql MYSQL_USER=${MYSQL_USER} MYSQL_PASSWORD=${MYSQL_PASSWORD} MYSQL_PORT=3200 MYSQL_DATABASE=${MYSQL_DATABASE}
         npm run e2e:run
    artifacts:
        paths:
            - shopware/custom/plugins/${PLUGIN_NAME}/Tests/E2E/results/*
        expire_in: 1 week
        when: always

E2E 5.2:
    stage: E2E
    extends:
        - E2E
        - .phpunit_base_pre_v53
    variables:
        CHECKOUT_SHOPWARE_BRANCH: "5.2"
        CHECKOUT_COOKIE_CONSENT_MANAGER_BRANCH: "5.2.11-5.2.27"
