name: PHPUnit Tests

on:
    workflow_call:

jobs:
    call-test-workflow:
        strategy:
            matrix:
                include:
                    -   shopware-version: '5.7'
                        php-version: '7.4'
                        mysql-version: '8.0'
                    -   shopware-version: '5.7'
                        php-version: '8.2'
                        mysql-version: '8.0'

        uses: shopware5/docker-images-testing/.github/workflows/php-unit-tests-shopware.yml@main
        with:
            plugin-name: SwagPaymentPayPalUnified
            php-version: ${{ matrix.php-version }}
            shopware-version: ${{ matrix.shopware-version }}
            mysql-version: ${{ matrix.mysql-version }}
