name: PHPUnit Tests

on:
    workflow_call:

jobs:
    call-test-workflow:
        strategy:
            matrix:
                include:
                    -   shopware-version: '5.2'
                        php-version: '5.6'
                        mysql-version: '5.7'
                        consent-manager: '5.2.11-5.2.27'

                    -   shopware-version: '5.3'
                        php-version: '5.6'
                        mysql-version: '5.7'
                        consent-manager: '5.3.5-5.3.7'

                    -   shopware-version: '5.4'
                        php-version: '5.6'
                        mysql-version: '5.7'
                        consent-manager: '5.4.6'

                    -   shopware-version: '5.5'
                        php-version: '7.1'
                        mysql-version: '5.7'
                        consent-manager: '5.5.0-5.5.10'

                    -   shopware-version: '5.6'
                        php-version: '7.2'
                        mysql-version: '5.7'
                        consent-manager: 'none'


        uses: shopware5/docker-images-testing/.github/workflows/php-unit-tests-shopware.yml@main
        with:
            plugin-name: SwagPaymentPayPalUnified
            php-version: ${{ matrix.php-version }}
            shopware-version: ${{ matrix.shopware-version }}
            mysql-version: ${{ matrix.mysql-version }}
            consent-manager: ${{ matrix.consent-manager }}
